// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtb1HdS6WlnXbpx1DOZASsqZHaj-gDCFA',
    appId: '1:711700714261:web:f0ab26598dfe48c32d0f1c',
    messagingSenderId: '711700714261',
    projectId: 'fcm-app-d7d7d',
    authDomain: 'fcm-app-d7d7d.firebaseapp.com',
    storageBucket: 'fcm-app-d7d7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIVU0GiaEQFehCD8X6tQD1C9_G--1NxRk',
    appId: '1:711700714261:android:131f3c878d5079d12d0f1c',
    messagingSenderId: '711700714261',
    projectId: 'fcm-app-d7d7d',
    storageBucket: 'fcm-app-d7d7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrxKVqgFjwcDSAe8ouqdxtqpAI4eIkojE',
    appId: '1:711700714261:ios:4c7e1ea9496fe5c42d0f1c',
    messagingSenderId: '711700714261',
    projectId: 'fcm-app-d7d7d',
    storageBucket: 'fcm-app-d7d7d.firebasestorage.app',
    iosBundleId: 'com.example.fcmApp',
  );

}